"""Add tfa_secret to User model

Revision ID: 81021da0cc4b
Revises: 
Create Date: 2024-05-26 19:48:09.330968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81021da0cc4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('user') as batch_op:
        batch_op.add_column(sa.Column('tfa_secret', sa.String(length=32), nullable=False, server_default=''))
    # Remove the default value after adding the column
    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column('tfa_secret', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('tfa_secret')

    # ### end Alembic commands ###
